// Order Management
export const SUBMIT_PURCHASE_ORDER_REQUEST = 'SUBMIT_PURCHASE_ORDER_REQUEST';
export const SUBMIT_PURCHASE_ORDER_SUCCESS = 'SUBMIT_PURCHASE_ORDER_SUCCESS';
export const SUBMIT_PURCHASE_ORDER_FAILURE = 'SUBMIT_PURCHASE_ORDER_FAILURE';